### ISSUE TITLE
return sf-object instead of SpatialPolygonsDataFrame?

### ISSUE THREAD

**Issue by mhermans** [bnosac/BelgiumMaps.StatBel#1]
With the increasing standardisation of spatial R-packages on `sf`-objects, would it be a good idea to switch the default format?

I'm not sure if the small overhead of including `st_as_sf()` in scripts outweighs the downsides of switching the default format in the package. But if sf-objects would be the way to go, switching earlier breaks less code...

**Comment by jwijffels** [comment]
Of course but I think the small overhead of using st_as_sf does not compensate enough for the large effort that will need to be done in the documentation of the package ...
I have no intentions on doing this, unless I need to update the package because the government released new shapefiles (e.g. because some communes have joined)

**Comment by mhermans** [comment]
Understandable, thanks for the fast response.
